# Generated by Django 2.0.5 on 2018-05-15 15:15

import Inventario.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_auto_20180509_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='espacio',
            name='capacidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='espacio',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fechaPrestamo',
            field=models.DateField(default=Inventario.models.get_date),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='horaInicio',
            field=models.TimeField(default=Inventario.models.get_time),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='horaTermino',
            field=models.TimeField(default=Inventario.models.get_time),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fechaCreacion',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fechaReserva',
            field=models.DateField(default=Inventario.models.get_date),
        ),
        migrations.AddField(
            model_name='reserva',
            name='horaInicio',
            field=models.TimeField(default=Inventario.models.get_time),
        ),
        migrations.AddField(
            model_name='reserva',
            name='horaTermino',
            field=models.TimeField(default=Inventario.models.get_time),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='solicitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='solicitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
