# Generated by Django 2.0.5 on 2018-05-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0003_auto_20180515_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='foto',
            field=models.ImageField(default='imgarticulo/None/no-img.jpg', upload_to='static/imgarticulo/'),
        ),
    ]
