# Generated by Django 2.0.5 on 2018-06-07 06:35
from django.contrib.auth.hashers import make_password
from django.db import migrations


def make_admin_user(apps, schema_editor):
    Usuario = apps.get_model('Inventario', 'Usuario')
    Usuario.objects.create(email='admin@cei.cl', username='00000000-0', nombre='Super', apellido='Admin', esAdmin=True,
                           password=make_password('admin123'))


class Migration(migrations.Migration):
    dependencies = [
        ('Inventario', '0001_auto_20180607_0658'),
    ]

    operations = [
        migrations.RunPython(make_admin_user),
    ]
